This branch is the Final Capstone milestone to connect RAILS backend API with React frontend for Booking App
Melaku05/booking-app-backend pull request #34
Opened 2022-08-29 15:34 UTC by steveWDamesJr

Hello Reviewer 👋 
:sunglasses: This is @Melaku05's, @aboongm's, @steveWDamesJr 's, and @Ismailco's final milestone for the Hello-World build. :sunglasses:

In this Final Capstone, we were able to complete the following:

## Milestones

[Project Requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md) - distributed into milestones below:

### Booking-app-backend
- [x] Milestone 1: Setup the project for backend (group task) #1'
- [x] Milestone 2: Implement devise gem
- [x] Milestone 3: Rspec test user 
- [x] Milestone 4: Generate table and model for the Doctor (Melaku)
- [x] Milestone 5: Generate table and model for the Reservation (Ranjit)
- [x] Milestone 6: Rspec for Reservation (Ranjit)
- [x] Milestone 7: Rspec for Doctor (Melaku)
- [x] Milestone 8: Implement Rspec gem (Steve)
- [x] Milestone 9: Create Documentation (steve)

### Booking-app-frontend
- [x] Milestone 1: Setup the project for the frontend (group task)
- [x] Milestone 2: Node package manager dependencies (group task)
- [x] Milestone 3: Create login page (group task)
- [x] Milestone 4: Create navigation panel (group task)
- [x] Milestone 5: Create main page (Ranjit)
- [x] Milestone 6: Create details page (Melaku)
- [x] Milestone 7: Create Reservation page (Steve)
- [x] Milestone 8: Create my reservation page (Ismail)
- [x] Milestone 9: Create the redux store (group task)
- [x] Milestone 10: Create the doctor reducer (group task)
- [x] Milestone 11: Create the reservation reducer (group task)
- [x] Milestone 12: Create the login reducer (group task)

- [x] Debug linter errors

![Savings](https://media.giphy.com/media/9iCp3hK2jLT10x1eMd/giphy.gif)

Thank you for taking the time to review our PR :pray:

2022-08-29 17:49 UTC, vichuge reviewed
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

- I couldn't add the database using `rails db:create`. I consider I need a secret key or something related to installing the application locally. 🐶 
![image](https://user-images.githubusercontent.com/20563252/187249614-73143e54-ccce-40ea-8697-cdadb90b728b.png)

- For this same reason I wouldn't be able to check the tests, please consider having enough tests for all this project. 😄 

### Front-end

- Please, add a test on the FE, the tests are a good practice to avoid extra work for the future. 🐴 
![image](https://user-images.githubusercontent.com/20563252/187264289-7a22a883-76ad-4416-9790-96fd98aeac24.png)

- It looks like the app is required to use the Back-end to see the application running, because I got the issue for BE, I couldn't be able to see the next points (please, consider it for the next review):
1. Check if the website result looks exactly like the given design and use its colors and typographies (students could change only, titles, photos, and descriptions).
2. Check if API requests are done only when information is needed.
3. Check if data from API is parsed correctly.


You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-29 17:49 UTC, vichuge commented on db/schema.rb
> +    t.string "date"
- I highly recommend you use a date/DateTime value here. A string date could be good, but I consider is a better practice to use date here. 🐱

2022-08-29 17:49 UTC, vichuge commented on db/seeds.rb
> +}
- It looks like there aren't seeds, and I invite you to add some of them. At the same time, it wasn't clear to me why to add a JSON element on seeds, if you don't add seeds, I kindly invite you to remove this. 🐦

2022-08-29 17:49 UTC, vichuge commented on config/routes.rb
> +    resources :reservations
- I consider it a good idea to add `:only` statement here, including only the required methods for the application functionality 🐉

2022-08-30 09:02 UTC, mcrd25 requested changes
Hi @steveWDamesJr @Ismailco @aboongm @Melaku05 , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-08-30 09:02 UTC, mcrd25 commented on README.md
> +# Booking-app-backend
Consider mentioning your swagger documentation here (or anywhere you feel suits) so that persons can view documentation and know that it exists. If you have a live version, add a link to the docs here. README should have some sort of endpoint documentation. 
[OPTIONAL]

2022-08-30 09:02 UTC, mcrd25 commented on app/controllers/members_controller.rb
> +      # removed user: user to avoid lint error, but it's not necessary
It's good practice to remove commented-out code. If you need to refer to it in the future, you can always use the git history

2022-08-30 09:02 UTC, mcrd25 commented on db/schema.rb
> +    t.string "date"
I concur with the above comment. This should be a date value - if you are keeping it this way, you have to implement some error handling

2022-08-30 13:30 UTC, mcrd25 approved these changes
Hi team, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-08-31 15:00 UTC, merged